version: "3"

services:

  vsftpd:
    container_name: rockylinux_vsftpd
    build:
      context: .
      dockerfile: ./Dockerfile

      #args:
       #USER_ID: 997
       #GROUP_ID: 997
    restart: always
    ports:
      - 0.0.0.0:20:20
      - 0.0.0.0:21:21
      - 0.0.0.0:21100-21110:21100-21110
    volumes:
      - ./homes:/home/vsftpd
      #- ./vsftpd_conf:/etc/vsftpd
      #- /mnt/fuan_storage/datas:/home/vsftpd/
      - ./logs:/var/log

